# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pitt RAS
email: ras@pitt.edu
description: > # this means to ignore newlines until "baseurl:"
    Website for the University of Pittsburgh's Robotics and Automation Society
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pittras.org/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

include: ['_pages']

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

paginate: 3
paginate_path: "/page:num/"
